### ISSUE TITLE
Missing Arduino program for SF30

### ISSUE THREAD

**Issue by mehrazh** [LightWare-Optoelectronics/SampleLibrary#1]
I've went through various documentations at LightWare and few other places but I could not find a working program that interfaces Arduino with SF30 module. Would it be possible for you release a sample code for SF30 - Arduino serial interface?

**Comment by Rob2048** [comment]
Hi mehrazh,

I have added an SF30 arduino serial sample. Please let me know if you have any more questions.

https://github.com/LightWare-Optoelectronics/SampleLibrary/tree/master/sf30_arduino_serial

**Comment by mehrazh** [comment]
Thank you for your fast response. This is going to be very helpful.

**Comment by idrissiilias** [comment]
Hello Rob, 
Thank you for your helpful. 
Is possible to use this code with SF30 D ?
