### ISSUE TITLE
SF30 signal strength arduino sample code 

### ISSUE THREAD

**Issue by CriCh93** [LightWare-Optoelectronics/SampleLibrary#10]
Hello! Is there a way to get the intensity of the returned signal of each distance mesaurement of the SF30? If yes, could it be possible to have a sample code? Thanks in advance!

**Comment by Rob2048** [comment]
Yes it is possible. Can you tell me about the specific Arduino platform you are using and which model of SF30?

**Comment by CriCh93** [comment]
Thanks for the reply! I am using an arduino mega 2560 and the model is the
SF30C

Il Mar 9 Mar 2021, 09:37 Robert Gowans ***@***.***> ha
scritto:
