### ISSUE TITLE
lw20 Arduino example is not working.

### ISSUE THREAD

**Issue by cloudsolution1** [LightWare-Optoelectronics/SampleLibrary#11]
Hi, I have tried lw20 Arduino code for my SF20 device but never got a response from the module. Is that verified code?
Thanks.

**Comment by Rob2048** [comment]
Hi @cloudsolution1, please contact support@lightwarelidar.com with your question and as many details as possible about your setup. We will run through all trouble shooting steps with you.

**Comment by cloudsolution1** [comment]
Thanks Rob. I am driving it with STM32. I am trying I2C now, but how to set i2c address? 0x55 or ox66? The link you shared is not working on my end.

**Comment by Rob2048** [comment]
Are you saying you can not send emails to that address?
