### ISSUE TITLE
Working with SF000/B ?

### ISSUE THREAD

**Issue by emigomez** [LightWare-Optoelectronics/SampleLibrary#12]
Hi,

I was just wondering which of your projects you could use to work with an SF000/B lidar and how could you get it going? 
I would like to work in ubuntu with C++ and ROS1 but I don’t know if you have any projects prepared in this sense.

Thanks in advance

**Comment by druyang** [comment]
I opened a PR for the SF000/B on the Teensy 
https://github.com/LightWare-Optoelectronics/SampleLibrary/pull/13

This was working.
