### ISSUE TITLE
How to Change Parameters

### ISSUE THREAD

**Issue by AsternA** [LightWare-Optoelectronics/SampleLibrary#3]
Hey Guys, 

These examples are great but it missing how to change parameters,

for example, how do i send the character '?" to the LiDAR to see firmware, or how to send ?L and so forth.

Please help me as i am unable to send requests and change address or measuring frequency

thanks

**Comment by Rob2048** [comment]
Hi Astern,

May I ask which product and which communication interface you are using?

**Comment by AsternA** [comment]
Hey Rob,

It's LW20/I2C

S/N: S20-18540

Thanks
Almog

**Comment by Rob2048** [comment]
You can find an example here: https://github.com/LightWare-Optoelectronics/SampleLibrary/blob/master/lw20_arduino_i2c/lw20_arduino_i2c.ino

This sends just the '?' command, but can be extrapolated to any command in the LW20 manual.
