### ISSUE TITLE
Getting 20.6m all the way on sf30/d via usb serial

### ISSUE THREAD

**Issue by danaki** [LightWare-Optoelectronics/SampleLibrary#4]
Hello, I'm trying to run Pythong samples for reading distance thru binary protocol via Serial. It outputs 20.6 meters no matter where I point the device. At the same time older protocol publishing distance in text in similar fashion does respond with correct distance reading and LightwareStudio also works as expected, so device is not damaged. What could be the problem?

**Comment by Rob2048** [comment]
Hi Yuri,

Please let me know which sample you used so I can check it.

**Comment by danaki** [comment]
* SampleLibrary/binary protocol/sf30_lwnx/sf30_lwnx.py
* SampleLibrary/binary protocol/python_lwnx_serial/lwnx.py

**Comment by danaki** [comment]
@Rob2048 can you please confirm?

**Comment by Rob2048** [comment]
The command set for the SF30/D is slightly different to the previous SF30 devices. I have added a sample specifically for the SF30/D here: https://github.com/LightWare-Optoelectronics/SampleLibrary/blob/master/binary%20protocol/sf30d_lwnx/sf30d_lwnx.py

You can find the SF30/D command set here: https://support.lightware.co.za/sf30d

**Comment by danaki** [comment]
Works like charm

**Comment by danaki** [comment]
Btw is that ok?
```
# Set update rate to 78 readings per second.
print('Set update rate')
executeCommand(port, 76, 1, [8, 0])
```

76 != 78

**Comment by Rob2048** [comment]
Yes it is correct. If you look at the documentation the opcode for setting update rate is 76. The 78 readings/sec is value 8.

http://support.lightware.co.za/sf30d/#/command_detail?id=_76-update-rate

**Comment by danaki** [comment]
Yes, I've just checked it out. Thought you have a typo in the comment. Thanks.
